language: ruby
before_install:
  - gem update bundler
matrix:
  include:
    - rvm: 1.9.3
      gemfile: gemfiles/rails_4.gemfile
    - rvm: 2.3.4
      gemfile: gemfiles/rails_5.gemfile
script: bundle exec rake
